const g=document.querySelector('#game');
const S={q:0,score:0,sit:0,first:null,pairs:0,hp:100,lock:false,blocking:false,kingTimer:null,phase:0};
const Q=[
['On which date prince and princess married each other?',['11 April','27 april','22 may','18 june'],2],
['What was prince first impress of princess',['She\'s smart','She\'s pretty','She\'s lazy','She\'s a boy'],3],
['What would ur wife say if she is shy?',['Moon is beautiful','Meaw','Atoms r kewl/hawt','All of the above'],3],
['What is most important for a relationship?',['Looks','Chicks','Lust','Loyality'],3],
['What is princess dream?',['Go to a beach','Pet a cat','Eat ice-cream','Shower with prince husband (better dessert 😏)'],3],
['Prince dream home MUST have?',['Theatre room','Sauna room','Hall','Soundproof big bedroom with attached shower room 😏'],3],
['What\'s something that will make her upset?',['not saying I love u back','Kissing back','Hugging back','All of the above'],3],
['Which song is prince least favourite?',['Skyfall','Most songs by c418','Playful massacre song for wembu','Rickroll'],3],
['His is famous called as what by basement kids?',['Powerless guy','Pookie','Wolfy','Supreme torturer'],3],
['What is heroz most important Mission?',['Save his wife from "monsyeter"','Pet a wolf','Spend time with Princess\'s sister 🤨','Kill spiders'],0]
];
const situations=[
['If a clone of me appeared that was 20% more pretty and cooked better 5 star meals, but clearly lacked my chaotic energy humour, how long before you realized it wasn\'t the real me?',['Within seconds honey, c\'mon ilysm','Might take me a while to differentiate, till then I\'ll spend time w that shawty😍'],0],
['If I suddenly gained the ability to speak fluently to pigeons and decided to assemble a local bird spy team irl to do my detective work, would you join my bird empire ?',['No that\'s boring','Ofc love 😘, we\'ll be better than cbi'],1],
['If I got turned into a worm, would you keep me in a nice little box with fancy dirt, or would you take me everywhere in your pocket?',['You\'ll always be with me sweetheart','No ew you always be covered in mud , i would love u 😒😒'],0]
];
function page(x){g.innerHTML=`<div class="wrap">${x}</div>`} function start(){page(`<div class="hero">👑</div><h1>THE BOYFRIEND<br>BIRTHDAY QUEST</h1><p>Your Princess has been locked away by the Evil King.</p><p class="small">One Prince. One kingdom. One extremely suspicious amount of spiders.</p><button class="btn" onclick="trial1()">⚔️ ENTER THE KINGDOM</button>`)}
function trial1(){S.q=0;S.score=0;quiz()}
function quiz(){let q=Q[S.q];page(`<p class="small">THE FIRST TRIAL · ${S.q+1}/10</p><div class="progress"><i style="width:${(S.q/10)*100}%"></i></div><h2>🧠 PROVE YOU KNOW THE PRINCESS</h2><div class="box"><h3>${q[0]}</h3></div>${q[1].map((a,i)=>`<button class="btn" onclick="answer(${i})">${'ABCD'[i]}. ${a}</button>`).join('')}`)}
function answer(i){let q=Q[S.q],ok=i===q[2];if(ok)S.score++;page(`<div class="hero">${ok?'💗':'😭'}</div><h2>${ok?'CORRECT!':'WRONG ANSWER!'}</h2><p>${ok?'The Princess is impressed.':'The Evil King is taking notes. 👺'}</p><p class="small">Score: ${S.score}/${S.q+1}</p><button class="btn" onclick="${S.q<9?'S.q++;quiz()':'kingTaunt()'}">CONTINUE ➜</button>`)}
function kingTaunt(){page(`<div class="hero">👺</div><p class="small">THE EVIL KING</p><div class="box"><h2>“Damn. You’re certified husband material.”</h2><p>“...well, I still bet you can’t defeat me.”</p><p><b>“I’m the cruel MONSYETER KING, with the powers of the FINAL BOSS OF ALL SPIDERS COMBINED 👺”</b></p><h2>“FIGHT MEEEEEE, YOU LIL WOLF.” 🐺⚔️</h2></div><button class="btn" onclick="trial2()">🗝️ FACE THE SECOND TRIAL</button>`)}
function trial2(){S.sit=0;scenario()}
function scenario(){let q=situations[S.sit];page(`<p class="small">THE SECOND TRIAL · ${S.sit+1}/3</p><div class="progress"><i style="width:${(S.sit/3)*100}%"></i></div><h2>💗 THE HUSBAND TEST</h2><div class="box"><h3>${q[0]}</h3></div>${q[1].map((a,i)=>`<button class="btn" onclick="sitAnswer(${i})">${'AB'[i]}. ${a}</button>`).join('')}`)}
function sitAnswer(i){let q=situations[S.sit],ok=i===q[2];page(`<div class="hero">${ok?'🥹':'👺'}</div><h2>${ok?'THE PRINCESS APPROVES':'THE KING LAUGHS MENACINGLY'}</h2><p>${ok?'Correct. Certified lil wolf. 🐺❤️':'That answer has been added to the Evil King’s evidence.'}</p><button class="btn" onclick="${S.sit<2?'S.sit++;scenario()':'memory()'}">CONTINUE ➜</button>`)}
function memory(){S.first=null;S.lock=false;S.pairs=0;let a=['❤️','🌙','🎮','💌','⭐','👑'],arr=[...a,...a].sort(()=>Math.random()-.5);page(`<p class="small">THE THIRD TRIAL</p><h2>🧩 THE MEMORY GATE</h2><p class="small">Match the symbols to open the castle gate.</p><div class="grid">${arr.map(x=>`<button class="card" data-v="${x}" onclick="flip(this)">?</button>`).join('')}</div>`)}
function flip(el){if(S.lock||el.classList.contains('open'))return;el.classList.add('open');el.textContent=el.dataset.v;if(!S.first){S.first=el;return}let f=S.first;S.first=null;if(f.dataset.v===el.dataset.v){S.pairs++;f.disabled=el.disabled=true;if(S.pairs===6)setTimeout(bossIntro,450)}else{S.lock=true;setTimeout(()=>{f.classList.remove('open');el.classList.remove('open');f.textContent=el.textContent='?';S.lock=false},650)}}
function bossIntro(){page(`<div class="hero">🏰</div><h2>THE KING'S KEEP</h2><div class="box"><p>The castle doors open.</p><p>Behind them stands the MONSYETER KING.</p><p class="small">Your Princess is somewhere beyond him.</p></div><button class="btn" onclick="boss()">⚔️ FIGHT THE EVIL KING</button>`)}
function boss(){S.hp=100;S.phase=0;page(`<p class="small">FINAL BATTLE</p><div class="hpwrap">KING HP<div class="bar"><i id="hp" style="width:100%"></i></div></div><div id="arena" class="battle"><div class="warning" id="warn">THE KING IS WATCHING...</div><div class="fighter king" id="king">👺</div><div class="fighter prince" id="prince">🐺⚔️</div><div class="slash" id="slash"></div><div class="battleText" id="bt">Swipe left/right to dodge. Tap to strike. Hold to block.</div><div class="vignette"></div></div><div class="controls"><button class="btn" onclick="attack()">⚔️ STRIKE</button><button class="btn" onpointerdown="block(true)" onpointerup="block(false)" onpointercancel="block(false)">🛡️ HOLD BLOCK</button></div><p class="hint">Phone: swipe ←/→ to dodge, tap to strike, hold block. Desktop: A/D, click/Space, Shift.</p>`);setTimeout(kingAttack,1100);bindGestures()}
function bindGestures(){let a=document.querySelector('#arena'),x=0,y=0;a.onpointerdown=e=>{x=e.clientX;y=e.clientY};a.onpointerup=e=>{let dx=e.clientX-x,dy=e.clientY-y;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)){dodge(dx<0?'left':'right')}else if(Math.abs(dy)>50&&dy<0){attack()}else attack()}}
function setText(t){let e=document.querySelector('#bt');if(e)e.textContent=t}
function kingAttack(){if(S.hp<=0)return;let arena=document.querySelector('#arena');if(!arena)return;setText('THE KING RAISES HIS WEAPON... DODGE OR BLOCK!');document.querySelector('#warn').textContent='INCOMING';setTimeout(()=>{if(S.hp<=0)return;if(S.blocking){setText('BLOCKED. The impact rattles your shield.');}else{S.hp=Math.max(0,S.hp-18);setText('HIT! The King drives you backward.');arena.classList.add('shake');setTimeout(()=>arena.classList.remove('shake'),220)}updateHp();if(S.hp>0){setTimeout(()=>{document.querySelector('#warn').textContent='THE KING IS WATCHING...';kingAttack()},900)}},650)}
function updateHp(){let e=document.querySelector('#hp');if(e)e.style.width=S.hp+'%'}
function attack(){if(S.hp<=0)return;let k=document.querySelector('#king'),s=document.querySelector('#slash');if(k){k.style.transform='translateX(-28px) scale(1.08)';setTimeout(()=>k.style.transform='',140)}if(s){s.classList.remove('show');void s.offsetWidth;s.style.left='42%';s.style.top='48%';s.classList.add('show')}setText('DIRECT HIT! Keep moving, lil wolf. 🐺');S.phase++;if(S.phase%4===0){S.hp=Math.max(0,S.hp-8);updateHp();setText('CRITICAL OPENING! The King staggers.')}if(S.phase>=12)win()}
function dodge(dir){if(S.hp<=0)return;let p=document.querySelector('#prince');if(p){p.style.transform=`translateX(${dir==='left'?-80:80}px)`;setTimeout(()=>p.style.transform='',240)}setText(`You dodge ${dir}. The King misses by inches.`)}
function block(v){S.blocking=v;setText(v?'SHIELD UP. WAIT FOR THE IMPACT.':'Shield down. MOVE!')}
function win(){S.hp=0;updateHp();document.querySelector('#warn').textContent='THE KING FALLS';setText('The MONSYETER KING has been defeated.');setTimeout(code,1200)}
window.addEventListener('keydown',e=>{if(e.key==='a'||e.key==='ArrowLeft')dodge('left');if(e.key==='d'||e.key==='ArrowRight')dodge('right');if(e.code==='Space')attack();if(e.key==='Shift')block(true)});window.addEventListener('keyup',e=>{if(e.key==='Shift')block(false)});
function code(){page(`<div class="hero">👑</div><h1>THE PRINCESS IS FREE</h1><div class="box"><p>The Evil King has fallen.</p><p>But the final castle vault remains locked.</p><p>🔐 <b>FINAL CODE</b></p><p class="small">Prototype code for now: <b>2205</b> — we can replace this with your real relationship clue.</p></div><input id="code" class="input" placeholder="ENTER CODE"><button class="btn" onclick="checkCode()">🔓 UNLOCK THE VAULT</button><p id="err" class="small"></p>`)}
function checkCode(){if(document.querySelector('#code').value.trim()==='2205')gift();else document.querySelector('#err').textContent='Wrong code. The King may be gone, but he left one last trap. 👺'}
function gift(){page(`<div class="hero">🎁</div><h1>QUEST COMPLETE</h1><div class="box"><p>👺 Evil King: DEFEATED</p><p>👑 Princess: RESCUED</p><p>🐺 Prince: VICTORIOUS</p><p>❤️ Kingdom: SAFE</p><h2>One final reward awaits...</h2></div><button class="btn" onclick="video()">🎬 OPEN THE BIRTHDAY SURPRISE</button>`)}
function video(){page(`<div class="hero">🥹❤️</div><h1>YOU FOUND IT.</h1><div class="box"><h2>🎬 YOUR BIRTHDAY VIDEO</h2><p class="small">Replace this screen with your real video link/file when you're ready.</p></div><button class="btn" onclick="secret()">🕵️ FIND SECRET LEVEL</button>`)}
function secret(){page(`<div class="hero">🕵️</div><h2>SECRET LEVEL</h2><p>You defeated a spider-powered MONSYETER KING just to reach your princess.</p><p><b>You're my favourite idiot. ❤️</b></p><button class="btn" onclick="start()">↻ PLAY AGAIN</button>`)}
start();
