const g=document.querySelector('#game');
const S={q:0,score:0,sit:0,first:null,pairs:0,lock:false};
const Q=[
['On which date prince and princess married each other?',['11 April','27 april','22 may','18 june'],2],
['What was prince first impress of princess',["She's smart","She's pretty","She's lazy","She's a boy"],3],
['What would ur wife say if she is shy?',['Moon is beautiful','Meaw','Atoms r kewl/hawt','All of the above'],3],
['What is most important for a relationship?',['Looks','Chicks','Lust','Loyality'],3],
['What is princess dream?',['Go to a beach','Pet a cat','Eat ice-cream','Shower with prince husband (better dessert 😏)'],3],
['Prince dream home MUST have?',['Theatre room','Sauna room','Hall','Soundproof big bedroom with attached shower room 😏'],3],
["What's something that will make her upset?",['not saying I love u back','Kissing back','Hugging back','All of the above'],3],
['Which song is prince least favourite?',['Skyfall','Most songs by c418','Playful massacre song for wembu','Rickroll'],3],
['His is famous called as what by basement kids?',['Powerless guy','Pookie','Wolfy','Supreme torturer'],3],
['What is heroz most important Mission?',['Save his wife from "monsyeter"','Pet a wolf','Spend time with Princess\'s sister 🤨','Kill spiders'],0]
];
const situations=[
["If a clone of me appeared that was 20% more pretty and cooked better 5 star meals, but clearly lacked my chaotic energy humour, how long before you realized it wasn't the real me?",['Within seconds honey, c\'mon ilysm','Might take me a while to differentiate, till then I\'ll spend time w that shawty😍'],0],
["If I suddenly gained the ability to speak fluently to pigeons and decided to assemble a local bird spy team irl to do my detective work, would you join my bird empire ?",['No that\'s boring','Ofc love 😘, we\'ll be better than cbi'],1],
["If I got turned into a worm, would you keep me in a nice little box with fancy dirt, or would you take me everywhere in your pocket?",["You'll always be with me sweetheart",'No ew you always be covered in mud , i would love u 😒😒'],0]
];
function page(x){g.innerHTML=`<div class="wrap">${x}</div>`}
function start(){page(`<div class="hero">👑</div><h1>THE BOYFRIEND<br>BIRTHDAY QUEST</h1><p>Your Princess has been locked away by the Evil King.</p><p class="small">One Prince. One kingdom. One extremely suspicious amount of spiders.</p><button class="btn" onclick="trial1()">⚔️ ENTER THE KINGDOM</button>`)}
function trial1(){S.q=0;S.score=0;quiz()}
function quiz(){const q=Q[S.q];page(`<p class="small">THE FIRST TRIAL · ${S.q+1}/10</p><div class="progress"><i style="width:${S.q/10*100}%"></i></div><h2>🧠 PROVE YOU KNOW THE PRINCESS</h2><div class="box"><h3>${q[0]}</h3></div>${q[1].map((a,i)=>`<button class="btn" onclick="answer(${i})">${'ABCD'[i]}. ${a}</button>`).join('')}`)}
function answer(i){const q=Q[S.q],ok=i===q[2];if(ok)S.score++;page(`<div class="hero">${ok?'💗':'😭'}</div><h2>${ok?'CORRECT!':'WRONG ANSWER!'}</h2><p>${ok?'The Princess is impressed.':'The Evil King is taking notes. 👺'}</p><p class="small">Score: ${S.score}/${S.q+1}</p><button class="btn" onclick="${S.q<9?'S.q++;quiz()':'kingTaunt()'}">CONTINUE ➜</button>`)}
function kingTaunt(){page(`<div class="hero">👺</div><p class="small">THE EVIL KING</p><div class="box"><h2>“Damn. You’re certified husband material.”</h2><p>“...well, I still bet you can’t defeat me.”</p><p><b>“I’m the cruel MONSYETER KING, with the powers of the FINAL BOSS OF ALL SPIDERS COMBINED 👺”</b></p><h2>“FIGHT MEEEEEE, YOU LIL WOLF.” 🐺⚔️</h2></div><button class="btn" onclick="trial2()">🗝️ FACE THE SECOND TRIAL</button>`)}
function trial2(){S.sit=0;scenario()}
function scenario(){const q=situations[S.sit];page(`<p class="small">THE SECOND TRIAL · ${S.sit+1}/3</p><div class="progress"><i style="width:${S.sit/3*100}%"></i></div><h2>💗 THE HUSBAND TEST</h2><div class="box"><h3>${q[0]}</h3></div>${q[1].map((a,i)=>`<button class="btn" onclick="sitAnswer(${i})">${'AB'[i]}. ${a}</button>`).join('')}`)}
function sitAnswer(i){const q=situations[S.sit],ok=i===q[2];page(`<div class="hero">${ok?'🥹':'👺'}</div><h2>${ok?'THE PRINCESS APPROVES':'THE KING LAUGHS MENACINGLY'}</h2><p>${ok?'Correct. Certified lil wolf. 🐺❤️':'That answer has been added to the Evil King’s evidence.'}</p><button class="btn" onclick="${S.sit<2?'S.sit++;scenario()':'memory()'}">CONTINUE ➜</button>`)}
function memory(){S.first=null;S.lock=false;S.pairs=0;const a=['❤️','🌙','🎮','💌','⭐','👑'],arr=[...a,...a].sort(()=>Math.random()-.5);page(`<p class="small">THE THIRD TRIAL</p><h2>🧩 THE MEMORY GATE</h2><p class="small">Match the symbols to open the castle gate.</p><div class="grid">${arr.map((x,i)=>`<button class="card" data-v="${x}" onclick="flip(this)">?</button>`).join('')}</div>`)}
function flip(el){if(S.lock||el.disabled||el.classList.contains('open'))return;el.classList.add('open');el.textContent=el.dataset.v;if(!S.first){S.first=el;return}const f=S.first;S.first=null;if(f.dataset.v===el.dataset.v){S.pairs++;f.disabled=el.disabled=true;if(S.pairs===6)setTimeout(bossIntro,500)}else{S.lock=true;setTimeout(()=>{f.classList.remove('open');el.classList.remove('open');f.textContent='?';el.textContent='?';S.lock=false},650)}}
function bossIntro(){page(`<div class="hero">🏰</div><h2>THE KING'S KEEP</h2><div class="box"><p>The castle doors open.</p><p>Behind them stands the MONSYETER KING.</p><p class="small">Your Princess is somewhere beyond him.</p></div><button class="btn" onclick="boss()">⚔️ ENTER THE BATTLEFIELD</button>`)}

let B=null;
const WORLD={w:680,h:500,r:14,playerSpeed:185,kingSpeed:72,shotSpeed:410};
const WALLS=[
{x:105,y:40,w:28,h:135},{x:105,y:260,w:28,h:125},{x:205,y:90,w:130,h:28},{x:205,y:90,w:28,h:120},
{x:205,y:310,w:150,h:28},{x:327,y:310,w:28,h:120},{x:425,y:35,w:28,h:150},{x:425,y:270,w:28,h:125},
{x:510,y:150,w:110,h:28},{x:55,y:410,w:150,h:28},{x:470,y:410,w:150,h:28},{x:55,y:205,w:80,h:28}
];
function boss(){
 const maxHp=150+S.score*12;
 B={running:true,win:false,keys:{},shots:[],particles:[],last:performance.now(),kingTimer:0,player:{x:55,y:70,hp:maxHp,maxHp,dir:'right',shootCd:0,shield:false,inv:0},king:{x:610,y:350,hp:160,maxHp,dir:'left',shootCd:1.8,flash:0,dead:false},cleanup:null};
 page(`<p class="small">THE FINAL TRIAL</p><h2>⚔️ WOLFY VS THE MONSYETER KING</h2><div class="battleHud"><div><b>🐺 WOLFY · KNIGHT</b><div class="bar"><i id="php"></i></div><span id="pht"></span></div><div><b>👺 MONSYETER KING</b><div class="bar enemy"><i id="khp"></i></div><span id="kht"></span></div></div><div id="arena" class="mazeArena"><canvas id="battleCanvas"></canvas><div class="bossWarning" id="bossWarning">HIDE BEHIND THE WALLS</div><div class="battleText" id="battleText">Move through the castle. Aim toward the King and tap SHOOT.</div><div class="deathOverlay" id="death"></div></div><div class="battleControls"><div class="dpad"><button data-dir="up">▲</button><div><button data-dir="left">◀</button><button data-dir="down">▼</button><button data-dir="right">▶</button></div></div><div class="combatBtns"><button class="combat attackBtn" id="attackBtn">✨ SHOOT</button><button class="combat shieldBtn" id="shieldBtn">🛡️ SHIELD</button></div></div><p class="hint">Phone: hold a direction to move. Tap SHOOT to fire where Wolfy is facing. Hold SHIELD. Desktop: WASD/arrows · Space · Shift.</p>`);
 initBattle();
}
function initBattle(){const c=document.querySelector('#battleCanvas');B.canvas=c;B.ctx=c.getContext('2d');resizeBattle();bindBattleControls();updateHud();B.last=performance.now();B.raf=requestAnimationFrame(loop)}
function resizeBattle(){if(!B)return;const arena=document.querySelector('#arena'),r=arena.getBoundingClientRect(),d=Math.max(1,Math.min(2,devicePixelRatio||1));B.viewW=r.width;B.viewH=r.height;B.scale=Math.min(r.width/WORLD.w,r.height/WORLD.h);B.ox=(r.width-WORLD.w*B.scale)/2;B.oy=(r.height-WORLD.h*B.scale)/2;B.canvas.width=Math.floor(r.width*d);B.canvas.height=Math.floor(r.height*d);B.canvas.style.width=r.width+'px';B.canvas.style.height=r.height+'px';B.ctx.setTransform(d,0,0,d,0,0)}
function bindBattleControls(){
 const keydown=e=>{if(!B?.running)return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift',' '].includes(k))e.preventDefault();if(k===' '){shoot()}else B.keys[k]=true};
 const keyup=e=>{if(B)B.keys[e.key.toLowerCase()]=false};window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('resize',resizeBattle);
 document.querySelectorAll('[data-dir]').forEach(b=>{const d=b.dataset.dir;const on=e=>{e.preventDefault();B.keys[d]=true;b.setPointerCapture?.(e.pointerId)};const off=e=>{e.preventDefault();B.keys[d]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('lostpointercapture',off)});
 const a=document.querySelector('#attackBtn');a.addEventListener('pointerdown',e=>{e.preventDefault();shoot()});
 const sh=document.querySelector('#shieldBtn');const on=e=>{e.preventDefault();B.keys.shield=true;sh.setPointerCapture?.(e.pointerId)},off=e=>{e.preventDefault();B.keys.shield=false};sh.addEventListener('pointerdown',on);sh.addEventListener('pointerup',off);sh.addEventListener('pointercancel',off);sh.addEventListener('lostpointercapture',off);
 B.cleanup=()=>{window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('resize',resizeBattle);cancelAnimationFrame(B.raf)};
}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function circleRect(x,y,r,w){const cx=clamp(x,w.x,w.x+w.w),cy=clamp(y,w.y,w.y+w.h);return (x-cx)**2+(y-cy)**2<r*r}
function wallHit(x,y,r){return WALLS.some(w=>circleRect(x,y,r,w))}
function moveCircle(o,dx,dy,speed,dt,r){let len=Math.hypot(dx,dy);if(len){dx/=len;dy/=len}const step=speed*dt;const nx=clamp(o.x+dx*step,r,WORLD.w-r),ny=clamp(o.y+dy*step,r,WORLD.h-r);if(!wallHit(nx,o.y,r))o.x=nx;if(!wallHit(o.x,ny,r))o.y=ny}
function clearLine(a,b){for(const r of WALLS)if(segmentRect(a.x,a.y,b.x,b.y,r))return false;return true}
function segmentRect(x1,y1,x2,y2,r){let t0=0,t1=1,dx=x2-x1,dy=y2-y1;for(const [p,q] of [[-dx,x1-r.x],[dx,r.x+r.w-x1],[-dy,y1-r.y],[dy,r.y+r.h-y1]]){if(Math.abs(p)<1e-9){if(q<0)return false}else{const t=q/p;if(p<0){if(t>t1)return false;if(t>t0)t0=t}else{if(t<t0)return false;if(t<t1)t1=t}}}return t0<=t1}
function shoot(){if(!B?.running||B.player.shootCd>0)return;const p=B.player,k=B.king;let dx,dy;if(clearLine(p,k)){dx=k.x-p.x;dy=k.y-p.y}else{if(p.dir==='left')dx=-1,dy=0;else if(p.dir==='right')dx=1,dy=0;else if(p.dir==='up')dx=0,dy=-1;else dx=0,dy=1}const l=Math.hypot(dx,dy)||1;B.shots.push({x:p.x,y:p.y,vx:dx/l*WORLD.shotSpeed,vy:dy/l*WORLD.shotSpeed,owner:'p',life:0});p.shootCd=.32;burst(p.x,p.y,'#d9efff',5);msg(clearLine(p,k)?'✨ MAGIC SHOT — HIT THE KING!':'✨ MAGIC SHOT — GET AROUND THE WALL!')}
function kingShoot(){const p=B.player,k=B.king;if(!clearLine(k,p)){msg('🧱 The wall protects Wolfy.');return}const dx=p.x-k.x,dy=p.y-k.y,l=Math.hypot(dx,dy)||1;B.shots.push({x:k.x,y:k.y,vx:dx/l*WORLD.shotSpeed*.82,vy:dy/l*WORLD.shotSpeed*.82,owner:'k',life:0});k.shootCd=5;const w=document.querySelector('#bossWarning');if(w){w.textContent='⚠️ KING ATTACKS — HIDE!';w.classList.add('danger');setTimeout(()=>w.classList.remove('danger'),800)}msg('👺 THE KING THROWS HIS MAGIC WEAPON!')}
function update(dt){const p=B.player,k=B.king;if(!B.running)return;let dx=0,dy=0;if(B.keys.w||B.keys.arrowup||B.keys.up)dy--;if(B.keys.s||B.keys.arrowdown||B.keys.down)dy++;if(B.keys.a||B.keys.arrowleft||B.keys.left)dx--;if(B.keys.d||B.keys.arrowright||B.keys.right)dx++;if(dx||dy){if(Math.abs(dx)>Math.abs(dy))p.dir=dx>0?'right':'left';else p.dir=dy>0?'down':'up'}moveCircle(p,dx,dy,WORLD.playerSpeed,dt,WORLD.r);p.shield=!!B.keys.shield;p.shootCd=Math.max(0,p.shootCd-dt);p.inv=Math.max(0,p.inv-dt);k.flash=Math.max(0,k.flash-dt);if(!k.dead){let kdx=0,kdy=0;const d=Math.hypot(p.x-k.x,p.y-k.y);if(d>185){kdx=(p.x-k.x)/(d||1);kdy=(p.y-k.y)/(d||1)}else if(d<125){kdx=(k.x-p.x)/(d||1);kdy=(k.y-p.y)/(d||1)}moveCircle(k,kdx,kdy,WORLD.kingSpeed,dt,WORLD.r+3);if(Math.abs(kdx)>Math.abs(kdy))k.dir=kdx>0?'right':'left';else if(kdy)k.dir=kdy>0?'down':'up';k.shootCd=Math.max(0,k.shootCd-dt);if(k.shootCd<=0&&clearLine(k,p))kingShoot()}
 for(let i=B.shots.length-1;i>=0;i--){const s=B.shots[i];const ox=s.x,oy=s.y;s.x+=s.vx*dt;s.y+=s.vy*dt;s.life+=dt;if(s.x<0||s.x>WORLD.w||s.y<0||s.y>WORLD.h||WALLS.some(w=>segmentRect(ox,oy,s.x,s.y,w))){B.shots.splice(i,1);continue}const target=s.owner==='p'?k:p;if(!target.dead&&Math.hypot(s.x-target.x,s.y-target.y)<WORLD.r+8){B.shots.splice(i,1);if(s.owner==='p'){k.hp=Math.max(0,k.hp-20);k.flash=.15;burst(k.x,k.y,'#ffffff',12);msg(`💥 DIRECT HIT! KING HP −20`);if(k.hp<=0){winBattle();return}}else if(p.inv<=0){if(p.shield){p.inv=.2;burst(p.x,p.y,'#9ed5ff',10);msg('🛡️ BLOCKED!')}else{p.hp=Math.max(0,p.hp-15);p.inv=.65;burst(p.x,p.y,'#ff6878',10);msg('💥 WOLFY HIT! HIDE OR SHIELD!');if(p.hp<=0){loseBattle();return}}}}}
 updateParticles(dt);updateHud()}
function updateParticles(dt){for(let i=B.particles.length-1;i>=0;i--){const q=B.particles[i];q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;if(q.life<=0)B.particles.splice(i,1)}}
function burst(x,y,c,n){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=40+Math.random()*100;B.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35,c})}}
function msg(t){const e=document.querySelector('#battleText');if(e)e.textContent=t}
function updateHud(){if(!B)return;const a=document.querySelector('#php'),b=document.querySelector('#khp');if(a)a.style.width=`${B.player.hp/B.player.maxHp*100}%`;if(b)b.style.width=`${B.king.hp/B.king.maxHp*100}%`;const c=document.querySelector('#pht'),d=document.querySelector('#kht');if(c)c.textContent=`${Math.ceil(B.player.hp)}/${B.player.maxHp} HP`;if(d)d.textContent=`${Math.ceil(B.king.hp)}/${B.king.maxHp} HP`}
function loop(now){if(!B?.running)return;const dt=Math.min(.033,(now-B.last)/1000||0);B.last=now;update(dt);draw();B.raf=requestAnimationFrame(loop)}
function draw(){const ctx=B.ctx;ctx.setTransform(devicePixelRatio||1,0,0,devicePixelRatio||1,0,0);ctx.clearRect(0,0,B.viewW,B.viewH);ctx.save();ctx.translate(B.ox,B.oy);ctx.scale(B.scale,B.scale);ctx.fillStyle='#090b11';ctx.fillRect(0,0,WORLD.w,WORLD.h);for(let x=0;x<WORLD.w;x+=34)for(let y=0;y<WORLD.h;y+=34){ctx.fillStyle=(x/34+y/34)%2?'#11151c':'#0f1319';ctx.fillRect(x,y,33,33)}for(const w of WALLS){ctx.fillStyle='#303742';ctx.fillRect(w.x,w.y,w.w,w.h);ctx.fillStyle='#4d5664';ctx.fillRect(w.x,w.y,w.w,5)}for(const s of B.shots)drawShot(ctx,s);drawKnight(ctx,B.player);drawKing(ctx,B.king);for(const q of B.particles){ctx.globalAlpha=Math.max(0,q.life/.35);ctx.fillStyle=q.c;ctx.beginPath();ctx.arc(q.x,q.y,3,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.restore()}
function drawKnight(ctx,p){ctx.save();ctx.translate(p.x,p.y);if(p.inv>0)ctx.globalAlpha=.5;ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,14,19,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#652b3a';ctx.beginPath();ctx.moveTo(-15,2);ctx.lineTo(15,2);ctx.lineTo(18,18);ctx.lineTo(-18,18);ctx.closePath();ctx.fill();ctx.fillStyle='#d7dee8';ctx.beginPath();ctx.arc(0,-5,15,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1a2029';ctx.fillRect(-12,-9,24,6);ctx.fillStyle='#e4b84e';ctx.beginPath();ctx.moveTo(-11,-17);ctx.lineTo(-5,-27);ctx.lineTo(0,-18);ctx.lineTo(7,-28);ctx.lineTo(12,-17);ctx.closePath();ctx.fill();ctx.fillStyle='#a7dcff';ctx.shadowColor='#8bd4ff';ctx.shadowBlur=10;ctx.fillRect(12,-3,22,6);ctx.shadowBlur=0;ctx.restore()}
function drawKing(ctx,k){ctx.save();ctx.translate(k.x,k.y);if(k.flash>0)ctx.globalAlpha=.5;ctx.fillStyle='#0009';ctx.beginPath();ctx.ellipse(0,15,24,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#17191f';ctx.beginPath();ctx.moveTo(-21,0);ctx.lineTo(21,0);ctx.lineTo(18,28);ctx.lineTo(-18,28);ctx.closePath();ctx.fill();ctx.fillStyle='#592630';ctx.beginPath();ctx.arc(0,-8,17,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff4457';ctx.beginPath();ctx.arc(-7,-10,3,0,Math.PI*2);ctx.arc(7,-10,3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#c99c3d';ctx.beginPath();ctx.moveTo(-19,-20);ctx.lineTo(-11,-34);ctx.lineTo(-3,-22);ctx.lineTo(4,-35);ctx.lineTo(11,-22);ctx.lineTo(19,-20);ctx.closePath();ctx.fill();ctx.fillStyle='#ff5a68';ctx.shadowColor='#ff334d';ctx.shadowBlur=12;ctx.fillRect(-35,-3,22,6);ctx.shadowBlur=0;ctx.restore()}
function drawShot(ctx,s){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(Math.atan2(s.vy,s.vx));ctx.fillStyle=s.owner==='p'?'#eaf7ff':'#ff5263';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;ctx.fillRect(-10,-3,20,6);ctx.restore()}
function winBattle(){if(!B.running)return;B.running=false;B.king.dead=true;const death=document.querySelector('#death');if(death)death.innerHTML='<div class="deathKingBig">👺</div><div class="deathLine">“YES UR INDEED SUPREME TORTURER MANNN...”</div><div class="deathLine">“U DESERVE HERRR... LOL.”</div>';msg('THE MONSYETER KING FALLS...');setTimeout(reunion,2600)}
function loseBattle(){if(!B.running)return;B.running=false;B.cleanup?.();page(`<div class="hero">💔</div><h2>WOLFY FELL...</h2><p>The Princess is still waiting inside the castle.</p><button class="btn" onclick="boss()">⚔️ TRY AGAIN</button>`)}
function reunion(){page(`<div class="reunion"><div class="castleGlow">🏰</div><div class="reunionScene"><div class="person wolfy">🐺</div><div class="heartBurst">❤️</div><div class="person princess">👑</div></div><h1>YOU FOUND HER.</h1><div class="box"><h2>THE PRINCE & HIS PRINCESS</h2><p>The Evil King is gone.</p><p><b>Wolfy finally reaches his Princess.</b></p><p class="hug">🐺❤️🤗❤️👑</p><p><b>And finally... the hug he came for. 💕</b></p></div><button class="btn" onclick="birthdayEnd()">💕 ONE LAST THING...</button></div>`)}
function birthdayEnd(){page(`<div class="hero">👑💕</div><h1>GAME OVER</h1><div class="box"><h2>THERE'S A BIRTHDAY SURPRISE VIDEO FOR U LOVEE 💕</h2><p>You defeated the MONSYETER KING, saved your Princess, and completed the quest.</p><p class="small">Your Princess has something waiting for you outside the game. 🥹❤️</p></div><p class="small">THE END · WOLFY & HIS PRINCESS</p>`)}
start();
